# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Set variables once
variables:
  - group: 'vh-vsts-automation'  # another variable group
  - group: 'Azure AD Tenant - hearings.reform.hmcts.net'
  - name: service # name of a variable
    value: vh-app-api # value of the variable
  - name: keyVaultName # name of a variable
    value: 'vh-jb-test' # value of the variable

trigger:
- master
pr:
- master

jobs:
- job: 
  displayName: 'Registr AAD App'
  pool: Azure-VSTS-VS2017

  # Reference templae for setting up build tools
  steps:
  - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
    clean: true  # whether to fetch clean each time

  - powershell: git clone https://github.com/hmcts/vh-ps-modules.git
    displayName: 'Get PowerShel module source'


  - powershell: | 
      #Get-ChildItem -Recurse
      Install-Module AzureAD
      Install-Module AzureRM.KeyVault
      Copy-Item -Path $(System.DefaultWorkingDirectory)/*vh-ps-modules/AzureADApplicationRegistration -Destination "C:\Program Files\WindowsPowerShell\Modules" -Recurse -Force
    displayName: 'Import AzureADApplicationRegistration Module'


  - powershell: | 
     write-host ('{0}' -f '$(vh_teantid)')
     write-host ('{0}' -f '$(vh_vsts_automation_dev_AppId)')
     write-host ('{0}' -f '$(vh_vsts_automation_dev_CertThumbprit)')
     write-host ('{0}' -f '$(vh_azure_subscription_id_dev)')
     write-host ('{0}' -f '$(service)_$(environmentName)')
     write-host ('{0}' -f '$(keyVaultName)')
     write-host ('{0}' -f '$(vh_hearings_tenata_id)')
     write-host ('{0}' -f '$(vh_hearings_vsts_automation_AppId)')
     write-host ('{0}' -f '$(vh_hearings_vsts_automation_CertThumbprit)')
    displayName: 'Print variable values'


  - powershell: | 
     Invoke-AzureADApplicationRegistration `
     -AzureTenantId '$(vh_teantid)' `
     -AzureAdAppId '$(vh_vsts_automation_dev_AppId)' `
     -AzureAdAppCertificateThumbprint '$(vh_vsts_automation_dev_CertThumbprit)' `
     -AzureSubscriptionId '$(vh_azure_subscription_id_dev)' `
     -AzureADApplicationName '$(service)-$(environmentName)' `
     -AzureKeyVaultName '$(keyVaultName)' `
     -AzureTenantIdSecondary '$(vh_hearings_tenata_id)' `
     -AzureAdAppIdSecondary '$(vh_hearings_vsts_automation_AppId)' `
     -AzureAdAppCertificateThumbprintSecondary '$(vh_hearings_vsts_automation_CertThumbprit)' `
     -verbose
    displayName: 'Register AAD App'




