variables:
  - group: 'vh-vsts-automation'  # variable group
  - group: 'Azure AD Tenant - hearings.reform.hmcts.net'
  - group: 'vh-hearings-ssl-certificates'
  - group: 'vh-hearings-reform-hmcts-net-dns-zone'

  - name: serviceName 
    value: vh-book-hearing-client # name of the app to be registered

  - name: keyVaultName 
    value: 'vhcoreinfrahtpreview' # key vault name to for storing AAD app's details - appId, ClientSecret, etc.

  - name: resourceGroupName
    value: $(service)-$(environmentName) # resource group name for where the website is located

  - name: AppServicePlanName
    value: vh-core-infra-$(environmentName) # App Service Plan name

  - name: WebSiteName
    value: $(service)-$(environmentName)  # Web Site name

  - name: CustomHostname
    value: $(WebSiteName)$(AzureAppServiceWebSiteCustomDomainName) # custom hostname used by the website

  - name: AADAppReplyUrls
    value: https://$(WebSiteName)$(AzureAppServiceWebSiteCustomDomainName), https://$(WebSiteName)$(AzureAppServiceWebSiteCustomDomainName)/login, https://$(WebSiteName)$(AzureAppServiceWebSiteCustomDomainName)/dashboard, https://$(WebSiteName)$(AzureAppServiceWebSiteCustomDomainName)/logout #CSV list of replay urls


# GitHub Repo that conatins build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
  - repository: azureDevOpsTemplates
    type: github
    name: hmcts/azure-devops-templates/tree/aad-app-registration-template
    endpoint: 'GitHub connection 1'

trigger:
- master
pr:
- master

jobs:
- template: jobs/aadAppRegistration.yml@azureDevOpsTemplates # Template reference
  parameters:
    serviceName: $(sonarCloudProjectKey)

